name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2.7-slim
    
    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: Initialize git
      run: |
        git config --global --add safe.directory /__w/X-radia-metadata/X-radia-metadata
    
    - name: Analysing the code with pylint
      run: |
        pylint new_enhanced_interactive.py
