name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2.7-slim
    
    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==1.9.5  # Last version supporting Python 2.7
        pip install astroid==1.6.6  # Required for pylint 1.9.5
    
    - name: Initialize git
      run: |
        git config --global --add safe.directory /__w/X-radia-metadata/X-radia-metadata
    
    - name: Setup mock XradiaPy
      run: |
        mkdir -p tests/mocks
        cat > tests/mocks/XradiaPy.py << 'EOL'
        # Mock XradiaPy for linting purposes
        class XrmBasicDataSet:
            def ReadFile(self, path): pass
            def GetName(self): pass
            def IsInitializedCorrectly(self): pass
            def GetObjective(self): pass
            def GetPixelSize(self): pass
            def GetPower(self): pass
            def GetVoltage(self): pass
            def GetFilter(self): pass
            def GetBinning(self): pass
            def GetHeight(self): pass
            def GetWidth(self): pass
            def GetProjections(self): pass
            def GetAxesNames(self): pass
            def GetAxisPosition(self, idx, axis): pass
            def GetDate(self, idx): pass
            def GetDetectorToRADistance(self, idx): pass
            def GetSourceToRADistance(self, idx): pass
            def GetExposure(self, idx): pass
        class Data:
            XRMData = type('XRMData', (), {'XrmBasicDataSet': XrmBasicDataSet})
        EOL
        export PYTHONPATH=$PYTHONPATH:$PWD/tests/mocks
    
    - name: Create pylintrc file
      run: |
        echo "[MASTER]" > .pylintrc
        echo "py-version = 2.7" >> .pylintrc
        echo "ignore = CVS" >> .pylintrc
        echo "persistent = yes" >> .pylintrc
        echo "load-plugins = " >> .pylintrc
        echo "" >> .pylintrc
        echo "[MESSAGES CONTROL]" >> .pylintrc
        echo "disable = C0111,C0103,C0303,W0311,W0603,R0903,R0913,R0914,W0621,C0325,W0612,C0326,C0330,C0301,W0703,R0902,R0904,R0912,R0915,E1101" >> .pylintrc
        echo "" >> .pylintrc
        echo "[FORMAT]" >> .pylintrc
        echo "max-line-length = 120" >> .pylintrc
        echo "indent-string = '    '" >> .pylintrc
        echo "" >> .pylintrc
        echo "[IMPORTS]" >> .pylintrc
        echo "allow-any-import-level = yes" >> .pylintrc
    
    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=$PYTHONPATH:$PWD/tests/mocks find new_enhanced_interactive -type f -name "*.py" | xargs pylint --rcfile=.pylintrc
