name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2.7-slim
    
    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==1.9.5  # Last version supporting Python 2.7
        pip install astroid==1.6.6  # Required for pylint 1.9.5
        pip install XradiaPy
    
    - name: Initialize git
      run: |
        git config --global --add safe.directory /__w/X-radia-metadata/X-radia-metadata
    
    - name: Create pylintrc file
      run: |
        echo "[MASTER]" > .pylintrc
        echo "py-version = 2.7" >> .pylintrc
        echo "ignore = CVS" >> .pylintrc
        echo "persistent = yes" >> .pylintrc
        echo "load-plugins = " >> .pylintrc
        echo "" >> .pylintrc
        echo "[MESSAGES CONTROL]" >> .pylintrc
        echo "disable = C0111,C0103,C0303,W0311,W0603,R0903,R0913,R0914,W0621,C0325,W0612,C0326,C0330,C0301,W0703,R0902,R0904,R0912,R0915" >> .pylintrc
        echo "" >> .pylintrc
        echo "[FORMAT]" >> .pylintrc
        echo "max-line-length = 120" >> .pylintrc
        echo "indent-string = '    '" >> .pylintrc
        echo "" >> .pylintrc
        echo "[IMPORTS]" >> .pylintrc
        echo "allow-any-import-level = yes" >> .pylintrc
    
    - name: Analysing the code with pylint
      run: |
        find new_enhanced_interactive -type f -name "*.py" | xargs pylint --rcfile=.pylintrc
        pylint --rcfile=.pylintrc new_enhanced_interactive/main.py
